# Generated by Django 5.1.5 on 2025-02-04 23:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=50)),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.CharField(choices=[('S', 'spent'), ('R', 'received')], max_length=1)),
                ('date_completed', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(null=True)),
                ('date_expected', models.DateTimeField(null=True)),
                ('status', models.CharField(blank=True, choices=[('P', 'pending'), ('E', 'expected'), ('C', 'completed')], default='C', max_length=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.category')),
            ],
        ),
    ]
