# Generated by Django 5.1.5 on 2025-02-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='account',
            field=models.CharField(choices=[('R', 'received'), ('S', 'spent')], max_length=1),
        ),
    ]
