# Generated by Django 5.1.5 on 2025-02-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_transactions_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(blank=True, choices=[('E', 'expected'), ('C', 'completed'), ('P', 'pending')], default='C', max_length=1),
        ),
    ]
