# Generated by Django 5.2 on 2025-06-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_category_user_transactions_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
